### ISSUE TITLE
BooDark theme column unreadable comment value

### ISSUE THREAD

**Issue by yanickrochon** [phpmyadmin/themes#100]
I had to modify the CSS of that theme because the dark blue on grey was simply unreadable.

https://github.com/phpmyadmin/themes/blob/7d608b5f758c626e8099407d3dcdb4f04c91d63a/boodark/scss/_common.scss#L287

I changed the value to `#7df`. It's very close to the column header, but it's now readable and within the palette of the theme.

**Comment by adorade** [comment]
Solved. Included in the next release.
Thank you for using BooDark. 🥇

**Comment by yanickrochon** [comment]
Ah! Nice! Yes, this is related to the mentioned issue, closing this one. Thanks!

**Comment by williamdes** [comment]
I am re-opening it, and the PR on this repo will close it back when it's solved :)
