### ISSUE TITLE
Radio buttons have oval shape when calling a routine

### ISSUE THREAD

**Issue by jnko266** [phpmyadmin/themes#107]
...as title suggests - when calling a routine that accepts ENUM parameters, it renders these as radio buttons, but these get stretched to the width of other inputs for the routine, making it an oval shape. 

![image](https://github.com/phpmyadmin/themes/assets/33516559/e64afcc8-d36d-4670-ac2d-c457972a77d0)

I´m running PMA 5.2.1 with the darkwolf theme.

**Comment by williamdes** [comment]
Thank you for reporting this

/cc @SteppenWolf68

**Comment by jnko266** [comment]
I have a fix, simply add 

```
.rte_table input[type="radio"] {
	width: 1em;
    height: 1em;
}
```

to file `theme.css`

**Comment by jnko266** [comment]
#108
