### ISSUE TITLE
MHN theme gets stuck when its loaded at phpmyAdmin 4.7 & 4.8 @ demo server

### ISSUE THREAD

**Issue by edwarddekker** [phpmyadmin/themes#19]
@nijel @ibennetch,

Today i've tried to load a MHN theme at the demo server of phpMyAdmin.
The page seems not so well loaded into my browser.

I am viewing this demonstration with Mozilla Firefox v.51.0.1 (32-bits) and Windows 10 v1607 Build 14393.693 @ https://demo.phpmyadmin.net.

Regards,
Edward

**Comment by nijel** [comment]
If you mean on 4.7 branch, then it's the theme failure, it's not compatible with new version (I haven't yet looked at details).

**Comment by nijel** [comment]
Should be fixed by https://github.com/phpmyadmin/themes/pull/20.
