### ISSUE TITLE
Modernize pmahomme for PMA5

### ISSUE THREAD

**Issue by Dennis1993** [phpmyadmin/themes#33]
Hey guys,

I think we should update the default pmahomme theme. The current theme looks like 2000 and use so many Icons (page slowly). My idea is to create a modern theme without icons and very good performance. We can use Icons from Font Awesome (very good quality). Remove not used functions and reduce JQuery Code for better performance.

I looked a little bit around and found a skin called AdminLTE. I tested with it, maybe we can orient ourselves on this structure?

The goal should be to create a sleek, fast and modern design. It should use current browser techniques and we can't support older browsers anymore in my opinion.

Here's an example, as I imagine based on AdminLTE for tests:

![demo_pmahomme_modern](https://user-images.githubusercontent.com/1473674/61997871-46c7bc00-b0a8-11e9-9a05-3da379e8b489.png)

Does anyone have any ideas? :)

Thanks in advance for your answers

PS: Sorry for my bad english I'm from Germany :D

**Comment by williamdes** [comment]
You can have a look at the following links for icons
https://github.com/phpmyadmin/data/commit/2dd22f8956cb1a7fb89c3c0e6a9405279aedd8b6

https://github.com/phpmyadmin/phpmyadmin/pull/14318

IMO FontAwsome icons are not a good idea for the phpmyadmin project 

cc @ibennetch cc @mauriciofauth

**Comment by Dennis1993** [comment]
And now?

**Comment by williamdes** [comment]
Hi @Dennis1993 
We are implementing bootstrap and now have a bootstrap theme
scss is also used now
Maybe you could help us migrate to bootstrap and then implement your theme ;)
I would like to have a theme that uses the SVG icons but maybe compiled in a font like Font Awesome does

**Comment by X-Anonymous-Y** [comment]
any news on this theme? its look nice

**Comment by mauriciofauth** [comment]
@Dennis1993 Thank you for your suggestions.

> I think we should update the default pmahomme theme.

We will not change the design of the _pmahomme_ theme. For new designs is better to create a new theme.

> My idea is to create a modern theme without icons and very good performance. We can use Icons from Font Awesome (very good quality).

> The goal should be to create a sleek, fast and modern design.

You can create a new theme following this idea if you want. :wink:

> Remove not used functions and reduce JQuery Code for better performance.

You can open a new pull request in the [phpmyadmin repository](https://github.com/phpmyadmin/phpmyadmin) to help with that.

> maybe we can orient ourselves on this structure?

Themes only change the style (CSS). Any layout changes (HTML) should go to the [phpmyadmin repository](https://github.com/phpmyadmin/phpmyadmin) and will affect all themes.

**Comment by williamdes** [comment]
Hi @Dennis1993
Quite some work was done and the migration to bootstrap is quite well advanced
Let us know your thoughts about this one

Do you consider this request complete since you closed it?
