### ISSUE TITLE
Support for phpMyAdmin 5.x

### ISSUE THREAD

**Issue by SjamonDaal** [phpmyadmin/themes#42]
Hi,

Are you guys planning to support phpMyAdmin 5.x?

**Comment by ibennetch** [comment]
With which theme specifically? Many of these are quite old and the work required to bring the entire repository up to date with version 5.0 is extensive, but there are a couple that wouldn't take too much work.

I certainly love having themes available, and one of my bigger disappointments is that the theme engine makes it a bit difficult to keep themes updated.

**Comment by SjamonDaal** [comment]
The specific theme I used is fallen. It completely broke when enabled.

**Comment by zoran-grujic** [comment]
I made **dark** version of pmahomme v5.0:

https://github.com/zoran-grujic/pmahomme-dark-5.0

I have no idea how to add it by the pull request to the main repository...

**Comment by williamdes** [comment]
I think there is nothing more to do about this request, I am closing it.

> I have no idea how to add it by the pull request to the main repository...

The README now explains all you may want to know
