### ISSUE TITLE
Please add DARK theme.

### ISSUE THREAD

**Issue by korenevskiy** [phpmyadmin/themes#43]

**Comment by williamdes** [comment]
I transferred this issue here

**Comment by ibennetch** [comment]
Hi, I'm pleased that several members of the community have come up with dark themes, which you can find in the theme download area at https://www.phpmyadmin.net/themes/

**Comment by korenevskiy** [comment]
> Hi, I'm pleased that several members of the community have come up with dark themes, which you can find in the theme download area at https://www.phpmyadmin.net/themes/

Are you kidding? what is the use of your link when 95% of people use phpmyadmin built-in site hosting personal account. of course, there will be a standard theme. You're so good at making decisions. I've already seen this link. I ask you to embed the dark theme in the base archive.

**Comment by williamdes** [comment]
> Please add DARK theme.

This was your only claim.

> Are you kidding?

:scream: 

> I ask you to embed the dark theme in the base archive.

Please add a description to your issue next time.

**Comment by n-st** [comment]
I agree that this issue could have been worded more constructively, but I hope that doesn't bring you to discard the idea completely…

Would it be possible to pick one of those community-provided dark themes and integrate it into the official phpmyadmin releases?
That would make it easier to use out of the box, and make it available where the user has no control over the phpmyadmin installation (e.g. as a shared hosting customer).

**Comment by ibennetch** [comment]
> Would it be possible to pick one of those community-provided dark themes and integrate it into the official phpmyadmin releases?

We are considering it. Having a dark theme would be a nice improvement.
