### ISSUE TITLE
How to convert php to css?

### ISSUE THREAD

**Issue by lonagi** [phpmyadmin/themes#50]
If I put theme to folder /usr/share/phpmyadmin/themes, I don't see theme in settings, because each them doesn't have theme.json + css files

**Comment by ibennetch** [comment]
From where did you get the additional theme?

Which phpMyAdmin version are you using?

**Comment by lonagi** [comment]
> From where did you get the additional theme? Which phpMyAdmin version are you using?

1st computer has 4.8
2nd one has 4.9

**Comment by ibennetch** [comment]
And which additional theme are you trying to use?

**Comment by lonagi** [comment]
> And which additional theme are you trying to use?

I downloaded all themes. After that I checked my /themes folder. I found original and pmahomme folders. They contains theme.json and good css files. 

Next, I copy all folders to the /themes. Refresh phpmyadmin. Then I see none of them worked. No one is in list.

**Comment by lonagi** [comment]
It's my failure. My themes were only under read privs :3

Friends, if you have the same problem, check you rights to files

**Comment by ibennetch** [comment]
I'm so glad you solved the problem! Thanks for letting us know what the
solution was.
