### ISSUE TITLE
DarkWolf  Theme - Phpmyadmin 5.0/5.0.4

### ISSUE THREAD

**Issue by SteppenWolf68** [phpmyadmin/themes#52]
DarkWolf  Theme - Phpmyadmin 5.0/5.0.4
[darkwolf.zip](https://github.com/phpmyadmin/themes/files/5539643/darkwolf.zip)
![screen](https://user-images.githubusercontent.com/74430625/99129103-42435180-25d2-11eb-908f-9c9108e09065.png)

**Comment by ibennetch** [comment]
darkwolf has now been published at https://www.phpmyadmin.net/themes/
