### ISSUE TITLE
DarkWolf theme - PhpMyadmin 5.0 / 5.0.4

### ISSUE THREAD

**Issue by SteppenWolf68** [phpmyadmin/themes#54]
Upload file and fix:
extension: .zip
json: name theme, name autor, description and url
[darkwolf.zip](https://github.com/phpmyadmin/themes/files/5542601/darkwolf.zip)

I have done this project during the quarantine, I hope you like it
Thanks for your comments.

**Comment by ibennetch** [comment]
Thanks, I've updated my branch with your changes. I'll work on releasing it soon.

**Comment by SteppenWolf68** [comment]
> Thanks, I've updated my branch with your changes. I'll work on releasing it soon.

Thank you, I really appreciate it.

**Comment by ibennetch** [comment]
darkwolf has now been published at https://www.phpmyadmin.net/themes/

**Comment by SteppenWolf68** [comment]
> darkwolf has now been published at https://www.phpmyadmin.net/themes/

Thank you very much, I appreciate your help.

**Comment by sistemasCTEX** [comment]
Please

**Comment by sistemasCTEX** [comment]
Hi, i don't know where report this issue, but i don't know why in the structure of tables view the type column just show the header but the content of every row doesn't, just happen with this theme, i'm a fan of dark themes and i'm glad to be published for this version but this issue maybe could be fixed. Thanks
