### ISSUE TITLE
Darkwolf Theme For PhpMyadmin 5.0 fixed type column in the structure of tables

### ISSUE THREAD

**Issue by SteppenWolf68** [phpmyadmin/themes#58]
Hi, i don't know where report this issue, but i don't know why in the structure of tables view the type column just show the header but the content of every row doesn't, just happen with this theme, i'm a fan of dark themes and i'm glad to be published for this version but this issue maybe could be fixed. Thanks

_Originally posted by @sistemasCTEX in https://github.com/phpmyadmin/themes/issues/54#issuecomment-734940285_

**Comment by SteppenWolf68** [comment]
Hi @sistemasCTEX the problem is fixed. You can download now from here, while it is updated in the official page of phpmyadmin/themes.

Hi @ibennetch Could you update the files in the official page of phpmyadmin/themes please, I will appreciate it very much.

[darkwolf.zip](https://github.com/phpmyadmin/themes/files/5609347/darkwolf.zip)

**Comment by williamdes** [comment]
Hi @SteppenWolf68 
I did the pull-request in https://github.com/phpmyadmin/themes/pull/59, please check if everything is okay :)

**Comment by SteppenWolf68** [comment]
> Hi @SteppenWolf68
> I did the pull-request in #59, please check if everything is okay :)

Hi @williamdes 
The changes are correct, thanks! :)

**Comment by YouveGotMeowxy** [comment]
@SteppenWolf68 I just installed this theme, any idea why the icons look like this?

![image](https://user-images.githubusercontent.com/39491297/102892175-1c0c9f00-4425-11eb-8d17-6fcc44dacd45.png)

The inspector shows all the broken images have this .gif img in them:

![image](https://user-images.githubusercontent.com/39491297/102892273-3f374e80-4425-11eb-9c8f-7f4dc612ef12.png)

I have PMA running in a Docker container in WSL2, and mounted the theme folder to the container. The folder structure looks like this:

![image](https://user-images.githubusercontent.com/39491297/102892435-79a0eb80-4425-11eb-8975-f45d77757e20.png)

**Comment by williamdes** [comment]
cc @ibennetch for a merge and a new version please :)

**Comment by williamdes** [comment]
#65 will need to follow
