### ISSUE TITLE
darkwolf-5.1 Theme dark for phpmyadmin 5.1

### ISSUE THREAD

**Issue by SteppenWolf68** [phpmyadmin/themes#65]
Hi @williamdes, Hi @ibennetch

Could you please review the files for the darkwolf-5.1 theme for phpmyadmin 5.1 and if everything is correct I will appreciate it if you share it in phpmyadmin / themes and in phpmyadmin.net I appreciate your attention, greetings.

[darkwolf-5.1.zip](https://github.com/phpmyadmin/themes/files/6102269/darkwolf-5.1.zip)

**Comment by williamdes** [comment]
Hi @SteppenWolf68 
Thank you for the update !
As soon as #59 is merged and released your update will be uploaded and released afterwards

**Comment by ibennetch** [comment]
Our theme download engine deals well with different versions, so I would prefer to call this "darkwolf"  instead of "darkwolf-5.1" if no one objects.

**Comment by SteppenWolf68** [comment]
Hi @williamdes, Hi @ibennetch

darkwolf and darkwolf-5.1 are different themes for different versions of phpmyadmin

**Comment by SteppenWolf68** [comment]
> Our theme download engine deals well with different versions, so I would prefer to call this "darkwolf" instead of "darkwolf-5.1" if no one objects.

For me there is no problem

**Comment by SteppenWolf68** [comment]
I really appreciate your help, comments and suggestions.

**Comment by ibennetch** [comment]
I've just released [5.0.1](https://www.phpmyadmin.net/themes/#pma_5_0) with 5.0 support, with the fixes from @williamdes e310fc0477e336cd198c1bdb245a0b5a58de26aa.

I've also released [5.1](https://www.phpmyadmin.net/themes/#pma_5_1), our first add-on theme for 5.1.

Thank you for your work and contributions!

**Comment by BouRock** [comment]
Hello @SteppenWolf68, 

Thank you for this nice theme. It is beatiful. There is an issue with welcome page for my language. In some languages "Welcome to" comes after "phpMyAdmin" so it looks like as in the screenshot

![MaxthonSnap20210410131409](https://user-images.githubusercontent.com/11577799/114266460-2c11b400-99ff-11eb-982a-a3666dc56d56.png)
So "phpMyAdmin" is an image in this theme. How can we solve?

But It needs to be look as in the original or metro theme:

![MaxthonSnap20210410131720](https://user-images.githubusercontent.com/11577799/114266522-6e3af580-99ff-11eb-9104-30d14f560e6c.png)

**Comment by SteppenWolf68** [comment]
> Hello @SteppenWolf68,
> 
> Thank you for this nice theme. It is beatiful. There is an issue with welcome page for my language. In some languages "Welcome to" comes after "phpMyAdmin" so it looks like as in the screenshot
> 
> ![MaxthonSnap20210410131409](https://user-images.githubusercontent.com/11577799/114266460-2c11b400-99ff-11eb-982a-a3666dc56d56.png)
> So "phpMyAdmin" is an image in this theme. How can we solve?
> 
> But It needs to be look as in the original or metro theme:
> 
> ![MaxthonSnap20210410131720](https://user-images.githubusercontent.com/11577799/114266522-6e3af580-99ff-11eb-9104-30d14f560e6c.png)

Hi @BouRock,
Thank you for your comments,
You can solve the problem by removing or changing the following in theme.css >> h1 bdo {
display: none
}
Change it to >> h1 bdo {
display: inline
}
or just delete it. Hope this helps you, regards.

**Comment by BouRock** [comment]
Yes, thank you.
