### ISSUE TITLE
pmahomme dark

### ISSUE THREAD

**Issue by akincan147** [phpmyadmin/themes#66]
Dark version of default phpMyAdmin pmahomme theme

The pmahomme  theme has been completely changed to the dark theme. Just only color changes not re-created.

Here is the screen of theme:

![screen-large](https://user-images.githubusercontent.com/76741859/125277111-b5e05e80-e319-11eb-9ccf-2de2ab6f6208.png)

Here is the repo: [https://github.com/akincan147/pmahomme-dark](https://github.com/akincan147/pmahomme-dark)

**Comment by williamdes** [comment]
Hi
It really looks nice!
Could you make it compatible with 5.1 and 5.2(not released) ?

**Comment by akincan147** [comment]
> Hi
> It really looks nice!
> Could you make it compatible with 5.1 and 5.2(not released) ?

I can do.

**Comment by williamdes** [comment]
> > Hi
> > It really looks nice!
> > Could you make it compatible with 5.1 and 5.2(not released) ?
> 
> I can do.

Let me know if you need help, tips: `yarn run css-compile --watch`

**Comment by akincan147** [comment]
OK.  I'll let you know in case of any problems or when it's done.

**Comment by akincan147** [comment]
> > > Hi
> > > It really looks nice!
> > > Could you make it compatible with 5.1 and 5.2(not released) ?
> > 
> > I can do.
> 
> Let me know if you need help, tips: `yarn run css-compile --watch`

OK.  I'll let you know in case of any problems or when it's done.

**Comment by uwe1337** [comment]
hi, could you make it compatible with 5.1.1?

**Comment by williamdes** [comment]
I am closing this request until some news is given about this theme from it's author
