### ISSUE TITLE
darkwolf font size

### ISSUE THREAD

**Issue by alebalweb** [phpmyadmin/themes#67]
Hi,
font size of my form (and form) are really big... How can i set a smaller font size? I take a look to the css, but i'm not sure where to change...
https://ibb.co/wLqhGkZ

**Comment by williamdes** [comment]
Hi @alebalweb 
What version are you using ?

**Comment by alebalweb** [comment]
darkwolf 5.1 installed from phpmyadmin.net on this server https://ibb.co/QmqQ6fC

**Comment by alebalweb** [comment]
Also pmahomme have enormous texts...

**Comment by williamdes** [comment]
cc @SteppenWolf68

**Comment by SteppenWolf68** [comment]
> Also pmahomme have huge font size...

Hi @alebalweb ...
Font size did not change from original file pmahomme

**Comment by alebalweb** [comment]
:( And can't be changed?

**Comment by SteppenWolf68** [comment]
![captura](https://user-images.githubusercontent.com/74430625/130699940-0c0711a6-2210-466b-9bc8-cb1015f55e55.jpg)

screenshot at 1920x1080

**Comment by SteppenWolf68** [comment]
hi @alebalweb 

maybe it's the zoom in your browser

**Comment by alebalweb** [comment]
No, zoom 100%, the side bar is normal... just forms are exploded...

**Comment by SteppenWolf68** [comment]
hi @alebalweb ...
![captura2](https://user-images.githubusercontent.com/74430625/130701721-932914a2-8e74-48a3-b866-3d521d764159.jpg)

Please check this line 12188, it must be 1.2 em, you can change to 1em

**Comment by SteppenWolf68** [comment]
hi @alebalweb 

These changes must be made within the theme.css file

**Comment by SteppenWolf68** [comment]
cc @williamdes

**Comment by alebalweb** [comment]
half... the text is smaller, but the forms are still huge

**Comment by SteppenWolf68** [comment]
the size of the forms was not modified, the problem must be where you
have it installed

**Comment by SteppenWolf68** [comment]
https://user-images.githubusercontent.com/74430625/130699940-0c0711a6-2210-466b-9bc8-cb1015f55e55.jpg

**Comment by williamdes** [comment]
I did push the change but css files need to be re-built
Do you approve the theme for 5.1 versions as compatible ?

**Comment by SteppenWolf68** [comment]
> I did push the change but css files need to be re-built
> Do you approve the theme for 5.1 versions as compatible

hi @williamdes 
Yes i do

**Comment by SteppenWolf68** [comment]
hi @williamdes 
I believe that this topic can be considered closed,
unless there is something else pending, greetings

**Comment by williamdes** [comment]
> hi @williamdes I believe that this topic can be considered closed, unless there is something else pending, greetings

Hi @ibennetch 
Could you release the version I prepared ?
