### ISSUE TITLE
Support phpMyAdmin v.5.2 Fallen theme

### ISSUE THREAD

**Issue by matteovisotto** [phpmyadmin/themes#69]
Could you please support version 5.2 in Fallen theme?

**Comment by williamdes** [comment]
Hi @fransallen
Do you want to update the theme? 
The README links of the fallen theme are now 404

Hi @KiitoX
Since you did some updates on this theme, would you want to do this one too?

**Comment by KiitoX** [comment]
Sorry, it's been a long time since I last used phpmyadmin. I'm not able to help with that at this point

**Comment by williamdes** [comment]
I am closing this request as there was no answer from @fransallen
