### ISSUE TITLE
Update darkwolfbootstrap theme for phpMyAdmin 5.2

### ISSUE THREAD

**Issue by SteppenWolf68** [phpmyadmin/themes#76]
Hi....

Update for the darkwolfbootstrap theme, fixed minor details, such as font color, background color, margins as well as being able to change the size of the text areas (resize)

[darkwolfbootstrap.zip](https://github.com/phpmyadmin/themes/files/8993146/darkwolfbootstrap.zip)

I will appreciate any comment and in case of any detail, to be able to correct it as soon as possible, greetings.

**Comment by bagou4502** [comment]
Hi on your theme there are no  bar like

![image](https://user-images.githubusercontent.com/53863206/178253509-603e2418-70ae-46a3-bd30-f0f60f923dbc.png)

So we can t slide on left/right

**Comment by SteppenWolf68** [comment]
> Hi on your theme there are no bar like
> 
> ![image](https://user-images.githubusercontent.com/53863206/178253509-603e2418-70ae-46a3-bd30-f0f60f923dbc.png)
> 
> So we can t slide on left/right

Hi @bagou4502 

if you need the scrollbars just remove this in theme.css:

body {
    -ms-overflow-style: none; /* for Internet Explorer, Edge */ scrollbar-width: none; /* for Firefox */ overflow-y: scroll;
}
body::-webkit-scrollbar {
    display: none; /* for Chrome, Safari, and Opera */
}

**Comment by bagou4502** [comment]
![image](https://user-images.githubusercontent.com/53863206/178280512-40fd9b5f-e834-4555-915b-ff174181ec41.png)
now i have a white bg lmao

**Comment by bagou4502** [comment]
Okey thanks I didn't know this existed in css

Its work perfectly

**Comment by InformatiqueProg** [comment]
Hi @SteppenWolf68 
First, i use your theme for one year now and i want to say that i love it.

I find an typo error on `/pma/themes/darkwolfbootstrap/css/theme.css:3356`

![Capture2022-07-15 165127](https://user-images.githubusercontent.com/7933327/179248526-96cb7d32-42be-46ea-a8d0-cb937b7ebc8c.jpg)

**Comment by SteppenWolf68** [comment]
Hi @InformatiqueProg 

Thanks for your comments and thanks for spotting that little bug, it's now fixed.
I will upload the .zip file in a new issue with all the corrected details detected until today by all the participants, hopefully the administrators can give it a good point of view and be able to download it from https://www.phpmyadmin.net/themes

Cheers
