### ISSUE TITLE
Theme not showing up in xampp

### ISSUE THREAD

**Issue by hhmonar** [phpmyadmin/themes#79]
Hola estimados,

gracias por compartir su conocimiento.

tengo una consulta como aplico el tema en phpmyadmin, tengo ubuntu 22.04, descomprimi la contenido del tema en opt/lampp/phpmyadmin/themes, pero cuando lo cargo de nuevo el xampp no veo tema en el listado, no se que estoy haciendo mal.

gracias

**Comment by Puigdemunt** [comment]
Tienes que mirar si el tema es compatible con la versión de phpMyAdmin que tienes.
Abre el archivo theme.json y comprueba el apartado "supports"

**Comment by williamdes** [comment]
Hi @hhmonar 
Do not forget to write to us in English for more users to be able to assist you :)
I think the answer to your request was given so I will close this issue, feel free to comment back here if not.
