### ISSUE TITLE
new theme DarkOrange v5.2

### ISSUE THREAD

**Issue by abolfazlrvn** [phpmyadmin/themes#85]
new DarkOrange theme for phpMyAdmin V5.2 & 5.1
Replaces: #83 
Repository: https://github.com/abolfazlrvn/phpMyAdminDarkOrange

**Comment by abolfazlrvn** [comment]
@williamdes Thank you.

**Comment by williamdes** [comment]
Hi @abolfazlrvn 
I was about to finally test and merge your theme but it's invalid and is missing a `theme.json` file. Can you add it to your repository ?

**Comment by abolfazlrvn** [comment]
> Hi @abolfazlrvn I was about to finally test and merge your theme but it's invalid and is missing a `theme.json` file. Can you add it to your repository ?

Unfortunately, I had forgotten, thank you for your attention. added.

**Comment by williamdes** [comment]
Thank you, I merged your theme 🎉

**Comment by abolfazlrvn** [comment]
> Thank you, I merged your theme 🎉

Thank you, it makes me proud

**Comment by williamdes** [comment]
> > Thank you, I merged your theme 🎉
> 
> Thank you, it makes me proud

HI @ibennetch
Could you make a release on our website of this theme?
