### ISSUE TITLE
BooDark User Account display with many users

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/themes#89]
@adorade 

When there are too many users for one page of the User Account tab, the pagination area doesn't seem to fit with the rest of the theme (additionally, some characters are not visible by default):

<img width="658" alt="image" src="https://user-images.githubusercontent.com/1443710/197396718-40bd7e30-d519-4f9b-8f05-d82e9194f196.png">

**Comment by adorade** [comment]
@ibennetch new user accounts style

![user-account-good](https://user-images.githubusercontent.com/6474149/198133362-99d37a18-6ae0-418a-958c-64a1db988f9c.png)
