### ISSUE TITLE
BooDark - errors, bugs, features

### ISSUE THREAD

**Issue by adorade** [phpmyadmin/themes#92]
Hi @ibennetch  @williamdes

The BooDark theme is a new theme, currently under development, and I'm happy to get feedback from those who are already using it. Personally, while using it, I discover errors and bugs but also things that I would like to improve. Being a "dark-mode" theme, it's much more pleasing to the eyes.

In the next 2 weeks I plan to release a new, much improved version that will be much more stable. So if you find bugs, errors or want some improvements, please feel free to open a new issue, it would help me a lot. Thank you! :wink:

**Comment by williamdes** [comment]
![image](https://user-images.githubusercontent.com/7784660/199001127-5ec15d34-a21c-4bbe-9edd-86190f08f3aa.png)
I think this is confusion because the un-selected button is not clearly a button. Maybe borders would help

**Comment by adorade** [comment]
I'm a little confused. This is how it looks to me, BooDark v1.0.1. Please give me more information.

Normal:
![button-choose-file-server](https://user-images.githubusercontent.com/6474149/199009504-47c96cd4-b5e9-4f72-8caf-5e10fb654f74.png)

Focused:
![button-choose-file-focus-server](https://user-images.githubusercontent.com/6474149/199009582-782900ad-49e6-4746-b962-2884ae3eb783.png)

I assume it's about "Choose File", which should stand out better

**Comment by adorade** [comment]
I understand. I think I should update my `config.inc.php` with the default settings so I can test other things better. What are you saying now?

![button-select-file-to-import](https://user-images.githubusercontent.com/6474149/199043909-4d6d323b-334b-4963-87e3-718adb59bb75.png)

![button-select-file-to-import-2](https://user-images.githubusercontent.com/6474149/199045593-b524b19d-e05a-45c1-ad5f-0c4914a307ce.png)

I also put borders but it doesn't look so good:

![button-select-file-to-import-border](https://user-images.githubusercontent.com/6474149/199047207-349f256e-7f30-4f12-950a-fc7a6bda1d9c.png)

I prefer w/out borders. Like in Bootstrap theme.

**Comment by williamdes** [comment]
> I also put borders but it doesn't look so good:

I agree, maybe a border around the two buttons to make it clear there is two modes ?

**Comment by adorade** [comment]
I think you mean `nav-pills` to act like `btn-group`. Like this, w/out borders but with dark background, better solution:

![nav-pills-group-1](https://user-images.githubusercontent.com/6474149/199127302-a46389a9-a02b-4422-8b78-34ceb3e95fd2.png)
![nav-pills-group-2](https://user-images.githubusercontent.com/6474149/199127352-b9e46de4-328f-4521-9750-d5d87533f744.png)

**Comment by williamdes** [comment]
Wow, I like it. It really looks nice !

**Comment by adorade** [comment]
Included in next release 😉

**Comment by williamdes** [comment]
Was this fixed by #94 ?

**Comment by adorade** [comment]
BooDark theme appears in https://demo.phpmyadmin.net/STABLE/ ❤️ not in https://demo.phpmyadmin.net/QA_5_2/ 😢  (logged in as root with empty password).

My intention is to maintain the theme, to keep up with the changes made for version 5.2.x 🚀  and to prepare it for the future version 5.3.0. 🚀 🚀 🚀

**Comment by williamdes** [comment]
I added this on my todo list, there is something wrong with the demo server build script

**Comment by adorade** [comment]
Thanks... when you have time.
Also, new release v1.0.2 has not yet been uploaded to https://www.phpmyadmin.net/themes/

**Comment by williamdes** [comment]
I made a bunch of fixes to the demo update script, it should be okay now

**Comment by williamdes** [comment]
Here is a new bug (white body):
![image](https://user-images.githubusercontent.com/7784660/212913129-b1ef675a-46ed-447c-9540-e9a4ae19d697.png)

**Comment by adorade** [comment]
@williamdes Thank you for reporting this. I will check as soon as possible.
It seems that `#table_name_col_no_outer' should have some space around it.

![create_table](https://user-images.githubusercontent.com/6474149/213257837-364e69fd-5414-456e-8ea1-7536608685d0.png)

... and "Create table form" should have the same background-color

![create_table_form_1](https://user-images.githubusercontent.com/6474149/213262084-db0e69ad-c78b-4089-b03d-44b6662c8d23.png)
![create_table_form_2](https://user-images.githubusercontent.com/6474149/213262123-eae78cf3-4ae0-4459-baf8-c48412a97444.png)

**Comment by williamdes** [comment]
I found another one for you
![image](https://user-images.githubusercontent.com/7784660/213659607-20f70481-492a-4581-a4fa-5024c6c80d1d.png)

I think the background is too black and this made me think that it was a bug.

**Comment by adorade** [comment]
@williamdes Fixed in next release. 😉

**Comment by williamdes** [comment]
> @williamdes Fixed in next release. wink (#98)

Awesome !
Can you create a new issue to track the progress of this extension to be published on the website ?
