### ISSUE TITLE
New release of BooDark is not published on the website

### ISSUE THREAD

**Issue by adorade** [phpmyadmin/themes#99]
I checked [phpmyadmin.net/themes](https://www.phpmyadmin.net/themes/) and the new version of the BooDark theme is not published (v1.0.3). Only previous versions are present.

**Comment by adorade** [comment]
@ibennetch @williamdes 
Any news about this issue?
I just release a new version of BooDark (v1.1.0)

**Comment by williamdes** [comment]
> @ibennetch @williamdes Any news about this issue? I just release a new version of BooDark (v1.1.0)

I assigned @ibennetch for review on #102
Most probably it will get to the website right after that. But for now only @ibennetch can do theme releases

**Comment by adorade** [comment]
Thank you 💯

**Comment by williamdes** [comment]
Done in https://github.com/phpmyadmin/themes/pull/102#issuecomment-1635169009
